<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit; ?>
            <?php $hitokoto = file_get_contents('/hitokoto/'); ?>
<div class="kuang">
</div><!-- end #footer -->
<?php $this->footer(); ?>
</div> <!-- 结束class="full"-->
<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit; ?>
<div class="backwords">
<?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?><?php echo $hitokoto; ?>
</div>
</body>
</html>
